### PR TITLE
tests: Add tests to ToColor function

### PR DESCRIPTION
**Pull request by marcosinger**
Hi @balacode, 

Firstly thanks for this great package.

I'd like to help you and I've started adding some tests on `ToColor` function.
I implemented it in a different way from what you already have in the package, but in another hand [table driven tests](https://github.com/golang/go/wiki/TableDrivenTests) are a standard way to test in Go ecosystem.

Perhaps we could move the hex code to another private method, but let's keep it simple for now.

Feel free to reach me regarding any part of it.
Thanks again!

### CODE REVIEW

**Comment by marcosinger** [comment]
@balacode I didn't see you already added tests for almost all functions. I started code it last week and my repo was not synced. Sorry about it.

Since my code was done, I just updated this branch to avoid conflict, but it's up to you to accept/discuss about the work done here.

**Comment by balacode** [comment]
Hello Marco! Big thanks for your interest and contribution.

I'm going to add your test in a separate file, alongside my own test file. I'll rename my own file to `to_color_1.go` and yours to `to_color_2.go` There can't be too many unit tests! Let each test have its own layout: closure-driven or table-driven. Later we can deliberate on the best test formats.

Now, there are still enough other unit tests to be done. 😄  You can run `go test -coverprofile cover.out` followed by `go tool cover -html=cover.out` to see the lines that are not tested right now. Even though it's like 5%, these are interesting cases like error-handling code and SaveFile().

Also, there should be a specific test for each method, that tests each method in a clever way. Because just having code coverage is not rigorous enough. For that I'm going to edit `public_test.go` and add TODO for each method not yet tested.

Let me do that right now... I'll get back to you in a few minutes

**Comment by balacode** [comment]
I've edited `public_test.go` adding TODOs on methods that don't have unit tests.
I've also merged your work, with some minor changes:

I prefixed the custom error types with TMP (for now), because they'll be altered soon.
Custom errors are a good idea and cleaner to read. I'm trying to keep the file as short as possible, so I'm just planning on how to use them without introducing much boilerplate code. 

Thank you very much Marco, please sync your branch and hope to get more feedback from you soon.

**Comment by marcosinger** [comment]
sorry my delay @balacode. Great! I'll sync my fork in the weekend and grab some function to add unit test on it. Can I keep the table test driven approach as the default for the new ones?

**Comment by balacode** [comment]
Hi @marcosinger, yes write the tests in the style you prefer. Having different styles of testing is even better for testing. I'll leave the tests to you for now and work on fixing some bugs I discovered.

**Pull request merged**
